version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
  NuGetApiKey:
    secure: Ql19CstT9GvFNeSIAjXvgHXZg+/pNaYJ2jVkzde4LT2vwSyjiQgQ+M332wVYtu+r
cache:
- '%USERPROFILE%\.nuget\packages'
xamarin:
  email: andrewarnott@gmail.com
  password:
    secure: dWaYN3ShMMzKvXN0kx2UTYneK+QKaDHmXGUWvHAo/MI=
  android: true
  ios: true
before_build:
- ps: nuget restore src -Verbosity quiet
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
